<script>     
    CV_MODULE_NAME_URL="<?=CV_MODULE_NAME_URL?>";
    CV_API_URL="<?=CV_API_URL?>";
    CROOPER_PROFILE_PIC_ASPECT_RATIO="<?=CROOPER_PROFILE_PIC_ASPECT_RATIO?>";
    CV_UPLOADS_PUBLIC_FILE_DIR_PATH="<?=CV_UPLOADS_PUBLIC_FILE_DIR_PATH?>";    
</script>